# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>

sudo: false
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - zlib1g-dev
env:
  global:
   - secure: "El+OxTCS9B4lFKga36w4r33SnxXNPtbubLAJRldzIDcZJwZCmsW0E5OZs4Z9NZkUbX9bh02YHCLmmeufReu60+SLxC7mHTWaGS5gxh9N8Nk8KtYhpR5LcjZv2zRmcHIY6Ucc4gDm1rTXcXH1l1PqQnrj3gw9C9hGCJ3opIAEXjg="
script:
 - make clean && LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" make V=1

addons:
  coverity_scan:
    project:
      name: "ecsv/glide64-cache-extract"
      description: "Build submitted via Travis CI"
    notification_email: sven+coverity@narfation.org
    build_command_prepend: make clean
    build_command:  make V=1
    branch_pattern: coverity_scan

