# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Build

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zlib1g-dev
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make clean && LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" make V=1
